### ISSUE TITLE
404 from base url

### ISSUE THREAD

**Issue by JacquiManzi** [elastic/snyk-github-issue-creator#30]
Hello! Thanks for the excellent tool! I think I stumbled onto a recently introduced bug:

The Snyk API is producing a 404 after the latest changes in 2.1.3. Using the previous version works and I believe the issue might have to do with the changes to the base url here: https://github.com/elastic/snyk-github-issue-creator/pull/28/files#diff-f06d6f602e4d6e089526d08ef3799ea2589f481cb2d1aad69a4d7fb1b455363eR7

Note the double `/rest`
`https://api.snyk.io/rest/rest/`

Error:
```
✔ Loading GitHub repositories
⠇ Loading Snyk projectsError: Failed to paginate request for get https://api.snyk.io/rest/rest/orgs/[redacted], error: 404 - {"jsonapi":{"version":"1.0"},"errors":[{"id":[redacted],"links":{"about":"https://docs.snyk.io/more-info/error-catalog#snyk-openapi-0004"},"status":"404","code":"SNYK-OPENAPI-0004","title":"Not found","detail":"not found","meta":{"links":[]}}]}, response: [object Object]
    at paginateRestResponseData (/opt/homebrew/lib/node_modules/@elastic/snyk-github-issue-creator/lib/snyk.js:141:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Snyk.projects (/opt/homebrew/lib/node_modules/@elastic/snyk-github-issue-creator/lib/snyk.js:49:26)
    at async module.exports (/opt/homebrew/lib/node_modules/@elastic/snyk-github-issue-creator/lib/vulnerabilities.js:44:20)
    at async /opt/homebrew/lib/node_modules/@elastic/snyk-github-issue-creator/index.js:16:27
```

**Comment by watson** [comment]
Thanks for raising this. This issue was introduced in #28 (ping @jeramysoucy)
